---
- name: deployment
  hosts: hosts
  remote_user: johannes_esbjornsson
  become: true
  roles: 
    - docker
  tasks:
    - name: sync docker file dir
      synchronize: src=/var/lib/jenkins/jobs/Job1/builds/lastSuccessfulBuild/archive/ dest=/tmp/jenkinspipe

    - name: Build an image 
      docker_image:
        force: yes
        path: /tmp/jenkinspipe
        name: test_pipe
        tag: latest
        state: present

    - name: Running the container
      docker_container:
        name: test_pipe
        image: test_pipe:latest
        state: started
        ports:
          - 80:80

